### ISSUE TITLE
Unable to start Mahou Tsukai

### ISSUE THREAD

**Issue by Ratomas** [AllTheMods/atm6-sky#422]
The manual says to cut yourself and hit the key bind to begin. I set the key bind for Draw Mahoujin to numpad 5 since nothing else uses that key. Cut my self with the dagger and hit numpad 5 and nothing happens. I have tried on the ground and on the spell cloth, but nothing every happens. Running version 1.1.0 of the pack.

**Comment by stepsword** [comment]
this is probably a bug in mahou which is fixed on the latest mahou version (1.31.14), but probably hasn't worked its way into the pack yet

in the meantime, just use attuned gems to keep track of your mana - mana should still work, it just wont show the display

**Comment by Ratomas** [comment]
Ok giving the updated mod a try to see if that fixed the issue

**Comment by Ratomas** [comment]
Nope still doesn’t draw the Mahoujin or show a mana gauge softer updating the mod to 1.31.14.

**Comment by stepsword** [comment]
@Ratomas oh, sorry, I misread and thought you were having trouble seeing your mahou. if you cant draw a blood circle in ATM6 sky the usual cause is that you're trying to do it on slabs, when it needs to be a full block

**Comment by Ratomas** [comment]
Roflmao of course it was something simple that I was doing wrong….. Thanks I will try it on a full block and update this ticket in a few minutes…

**Comment by Ratomas** [comment]
Thanks that worked.
