### ISSUE TITLE
Version 1.0.5 crash on start on Intel Macbook Pro

### ISSUE THREAD

**Issue by jonasstenberg** [AllTheMods/atm6-sky#94]
**Describe the bug**
When launching version 1.0.5 within MultiMC it crashes on the "Final completion" step. 

**Screenshots**
<img width="855" alt="Screenshot 2021-03-27 at 11 04 24" src="https://user-images.githubusercontent.com/5079016/112717356-656cfe80-8eec-11eb-8274-1a7db638ee81.png">

**Additional context**
Here is the crash report:
https://pastebin.com/mqtJ8YiX

Many thanks for an awesome mod pack!

**Comment by Vertigo81** [comment]
I get the same thing.  On a 2019 intel i5 iMac

[crash-2021-03-27_06.36.50-client.txt](https://github.com/AllTheMods/atm6-sky/files/6215907/crash-2021-03-27_06.36.50-client.txt)
[crash-2021-03-27_06.38.28-client.txt](https://github.com/AllTheMods/atm6-sky/files/6215908/crash-2021-03-27_06.38.28-client.txt)

**Comment by joshcfcharvey** [comment]
The game crashed whilst unexpected error
Error: java.lang.UnsatisfiedLinkError: /private/var/folders/jx/bm8zthz16sn3x4d1v83vc8gm0000gn/T/imgui-java-natives_1616866397821/libimgui-java64.dylib: dlopen(/private/var/folders/jx/bm8zthz16sn3x4d1v83vc8gm0000gn/T/imgui-java-natives_1616866397821/libimgui-java64.dylib, 1): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
Exit Code: 255

is what shows up when trying to load all the mods 6 to the sky on a macbook running any mac os version, need urget fixing as no-one on mac os can access the pack

**Comment by desagas** [comment]
I can second this!! Here is my crash log:

[crash-2021-03-27_14.28.29-client.txt](https://github.com/AllTheMods/atm6-sky/files/6216368/crash-2021-03-27_14.28.29-client.txt)

**Comment by geisjj** [comment]
Exact same issue. No need to post the log. Hope this gets fixed soon.

**Comment by zhykzhykzhyk** [comment]
Remove "Blueprint" mod can fix this crash.

**Comment by geisjj** [comment]
Which mod is "Blueprint"? I can't find anything like that in the mod folder...

**Comment by desagas** [comment]
Yeah, @AlltheMods, I'd say you should remove the mod from the pack until it can be used without taking additional steps to connect/network it with the proper libraries. Currently, this alienating a big number in your community, something that is not common with ATM.

**Comment by desagas** [comment]
@geisjj bpm-1.0.2.71

**Comment by geisjj** [comment]
Thanks, found it and giving it a go...

**Comment by geisjj** [comment]
That did the trick!

**Comment by Vertigo81** [comment]
This looks relevant, from the Blueprint mod info
" 
Notice: This mod uses imgui-java to render it's interface, and because of that it requires native bindings for each platform, Window, Mac, and Linux. That simply means that the dependency's of the mod differ from platform to platform,"

Seems very likely this is the problem.  We need to make changes for the Mac platform, but I'm out of my depth here.

**Comment by WhitePhant0m** [comment]
I see, we'll be removing the mod for now then, we added it due to [this update](https://www.curseforge.com/minecraft/mc-mods/bpm/files/3250941) saying that it was fixed, but apparently it wasn't(don't have a way to test mac).

**Comment by desagas** [comment]
Well, if you ever need a tester, I am pretty much a homebody, and am usually lurking in the cord.

**Comment by desagas** [comment]
Oh, yes, and I did also try it with the latest release of the mod, and the same issue happened.

**Comment by Vertigo81** [comment]
It sounds like it's less that the mod doesn't work, and more that we need different dependencies to use it on a Mac, which means including different other mods in the modpack and different config?

**Comment by joshcfcharvey** [comment]
But if the mod doesn’t work on a platform should it be removed from the pack, reason being I can’t join a server I’m playing on because that mod is in the server pack and blocking joining?

**Comment by MrManiacc** [comment]
Hi all I'm the developer, of the mod. I was a afraid this would be a problem I get to actually test the update, I just assumed it would fix mac as I had added the dependency's.

**Comment by desagas** [comment]
I think the call is correct, it is the path that is being called that does not exist. Perhaps on  curse, the dependency may have not saved. Maybe check your project settings again to see if the dependency is labeled correctly.

**Comment by oly2o6** [comment]
should be reported to the mod author but should/is fixed if not next version

**Comment by MrManiacc** [comment]
### The method casuing. the crash. Only present on lwjgl.glfw version <= 3.2.2 

`Exception in thread "main" [18:38:30] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 
...
...
 Caused by: java.lang.NullPointerException: A required function is missing: glfwGetMonitorWorkarea
...
...
[18:38:30] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	... 16 more
`
### Why it's not working? Mojang libraries.

After a lot of testing I've realized the crash on mac is due to mojang them self supplying an old version of lwjgl/glfw. They give version **3.2.1** but the method described above is only present in 3.2.2. This mod will work granted the version <= 3.2.2 of lwjgl, glfw, and the natives are present. The reason it works on windows, for whatever reason you lwjgl 3.2.2 is shipped  out of the box. 

### Minecraft on mac natviely comes with version 3.2.1
<img width="411" alt="Screen Shot 2021-04-13 at 6 47 44 PM" src="https://user-images.githubusercontent.com/4280960/114630517-c2a4d600-9c88-11eb-9a19-c628234e5bf2.png">

### This was added over 2 years ago, it's time for mojang to update their libraries.

<img width="491" alt="Screen Shot 2021-04-13 at 6 53 05 PM" src="https://user-images.githubusercontent.com/4280960/114630907-93db2f80-9c89-11eb-89cd-ac6ab8471407.png">

the method _**glfwGetMonitorWorkarea**_ was added in version 3.2.2, and the library I use requires this.

**Comment by GhostToast811** [comment]
I'm still having this issue is there any other ways of fixing this
